### ISSUE TITLE
Panel disappearing

### ISSUE THREAD

**Issue by JSparrow93** [fthx/hot-bottom#1]
In gnome 45 on OpenSUSE Micro os The panel just disappears when this extension is enabled. not sure if OS or extension's interactions with gnome 45.

**Comment by fthx** [comment]
Yes that's a change:
https://extensions.gnome.org/extension/5099/hot-bottom/

If you want a classical one, I suggest Hot Edge by jdoda, so I ran for a different setup in this one.
If you don't want that but still want this extension, you can remove the panel's hiding stuff.
